### PR TITLE
fix compile error: #include <memory> for std::unique_ptr

### PR DESCRIPTION
**Pull request by shilkin**
gcc version 4.9.1

### CODE REVIEW

**Comment by shilkin** [comment]
The main changes:
1. Fix event loop copying in uvpp::Work constructor
2. Make assumption that interface of uvpp::Async should looks like uvpp::Work
    Use case:
    { 
         // start of some scope in thread A
         shared_ptr<Async> async = make_shared(loop); // reference counter on Async* == 1
         async->send([async]() mutable                             // reference counter on Async* == 2
         {
             // callback actions
             async.reset(); // selfdestroy in thread B (reference counter on Async* == 1 or 0)
         });
} // end of some scope in thread A (reference counter on Async* == 1 or 0)

**Comment by shilkin** [comment]
Stupid use case description. I meant some different thing:
        std::shared_ptr<uvpp::Async> async = std::make_shared<uvpp::Async>(loop);
        async->send([async]()
                    {
                        // actions...
                        async->close();
                    });

**Comment by shilkin** [comment]
Written in markdown:
```c
std::shared_ptruvpp::Async async = std::make_shareduvpp::Async(loop);
async->send([async]()
{
    // actions...
    async->close();
});

**Comment by shilkin** [comment]
The main changes:
1. Fix event loop copying in uvpp::Work constructor
2. Make assumption that interface of uvpp::Async should looks like uvpp::Work
    Use case:

``` c
{ 
         // start of some scope in thread A
         shared_ptr<Async> async = make_shared(loop); // reference counter on Async* == 1
         async->send([async]()        // reference counter on Async* == 2
         {
             // callback actions
             async->close(); // selfdestroy in thread B (reference counter on Async* == 1 or 0)
         });
} // end of some scope in thread A (reference counter on Async* == 1 or 0)
```

**Comment by germanosin** [comment]
thanks!

**Pull request merged**
